services:
  aichronos-web:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    container_name: aichronos-web
    image: ghcr.io/v-lastrucci-c/mii_cc_ugr-web:latest
    ports:
      - "5000:5000"
    env_file:
      - ./src/web/.env_production
    depends_on:
      - aichronos-api
      - aichronos-db
    command: >
      sh -c "flask init-db && flask run --host=0.0.0.0 --port=5000"

  aichronos-api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: aichronos-api
    image: ghcr.io/v-lastrucci-c/mii_cc_ugr-api:latest
    ports:
      - "8000:8000"
    env_file:
      - ./src/api/.env_production

  aichronos-db:
    image: postgres:15
    container_name: aichronos-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aichronos
      POSTGRES_PASSWORD: aichronos*
      POSTGRES_DB: aichronos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
