services:
- type: web
  name: MII_CC_UGR_WEB
  runtime: docker
  repo: https://github.com/v-lastrucci-c/MII_CC_UGR
  plan: free
  envVars:
  - key: SQLALCHEMY_DATABASE_URI
    sync: false
  - key: TESTING
    sync: false
  - key: SQLALCHEMY_TRACK_MODIFICATIONS
    sync: false
  - key: DEBUG
    sync: false
  - key: PORT
    sync: false
  - key: SECRET_KEY
    sync: false
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: ./src/web

- type: web
  name: MII_CC_UGR_API
  runtime: docker
  repo: https://github.com/v-lastrucci-c/MII_CC_UGR
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: OPENAI_API_KEY
    sync: false
  region: frankfurt
  dockerContext: .
  dockerfilePath: ./Dockerfile
  rootDir: ./src/api

databases:
- name: MII_CC_UGR_DB
  databaseName: aichronos_db
  user: aichronos
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "15"
