name: Python AIChronos Tests and Upload Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest

    env:
      OPENAI_MODEL: "gpt-4o-mini"
      AICHRONOS_PROMPT_PATH: "./app/internal/prompts/system_prompt.yml"
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.9"

    - name: Install Poetry
      run: |
        pip install poetry

    - name: Install dependencies of API
      working-directory: ./src/api
      run: |
        poetry install

    - name: Install dependencies of WEB
      working-directory: ./src/web
      run: |
        poetry install

    - name: Test API with Taskipy
      working-directory: ./src/api
      run: poetry run task test
    
    - name: Test WEB with Taskipy
      working-directory: ./src/web
      run: poetry run task test
    
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
