name: Docker Auto-Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: publish
        uses: soltys/publish-docker-compose@v1.0.0
        with:
          version: 'latest'
          docker_compose: 'docker-compose.build.yml'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"