name: AIChronos Test of Cluster and Publish to Github Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    name: Tests the Cluster and Publishes to Github Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
  
      - name: Test Cluster
        run: |
          chmod +x ./test_cluster.sh
          ./test_cluster.sh

      - name: Publish Docker Images to Github Packages
        uses: soltys/publish-docker-compose@v1.0.0
        with:
          version: 'latest'
          docker_compose: 'compose.yml'
          repo_token: "${{ secrets.AICHRONOS_TOKEN }}"
